config/routes.rb
SwimTeam2::Application.routes.draw do
  devise_for :users

  resources :events

  resources :seasons

  resources :splits

  resources :swimmers

  resources :families

  resources :teams

  resources :home
  
  root :to => 'home#index'
end

app/models/season.rb
class Season < ActiveRecord::Base
  attr_accessible :active, :end_date, :meet_date, :name, :start_date

  has_many :teams
  has_many :swimmers, :through => :teams

end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  load_and_authorize_resource
  # GET /seasons
  # GET /seasons.json
  def index
    @seasons = Season.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @seasons }
    end
  end

  # GET /seasons/1
  # GET /seasons/1.json
  def show
    @season = Season.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @season }
    end
  end

  # GET /seasons/new
  # GET /seasons/new.json
  def new
    @season = Season.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @season }
    end
  end

  # GET /seasons/1/edit
  def edit
    @season = Season.find(params[:id])
  end

  # POST /seasons
  # POST /seasons.json
  def create
    @season = Season.new(params[:season])

    respond_to do |format|
      if @season.save
        format.html { redirect_to @season, notice: 'Season was successfully created.' }
        format.json { render json: @season, status: :created, location: @season }
      else
        format.html { render action: "new" }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /seasons/1
  # PUT /seasons/1.json
  def update
    @season = Season.find(params[:id])

    respond_to do |format|
      if @season.update_attributes(params[:season])
        format.html { redirect_to seasons_url, notice: 'Season was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1
  # DELETE /seasons/1.json
  def destroy
    @season = Season.find(params[:id])
    @season.destroy

    respond_to do |format|
      format.html { redirect_to seasons_url }
      format.json { head :no_content }
    end
  end

  before_filter :authenticate_user!
  
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_form.html.erb
<%= form_for(@season, :html => { :name => "timeform", :class => "form-horizontal well"}) do |f| %>
  <% if @season.errors.any? %>
    <div class="alert alert-error" id="error_explanation">
      <%= link_to "x", "#", :class=>"close", :onclick => "document.getElementById('error').style.display='none'" %> 
      <strong>Error! </strong><%= pluralize(@season.errors.count, "error") %> prohibited this season from being saved:
      <ul>
      <% @season.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :start_date, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :start_date, :class => "date_picker" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :end_date, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :end_date, :class => "date_picker" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :meet_date, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :meet_date, :class => "date_picker" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :active, :class => "control-label" %>
    <div class="controls">
      <%= f.check_box :active, :class=>"checkbox" %>
    </div>
  </div>
  <div class="control-group actions">
    <div class="controls">
      <%= f.submit(:class=>"btn btn-success") %>
    </div>
  </div>
<% end %>

app/views/seasons/edit.html.erb
<h1>Editing season</h1>

<%= render 'form' %>

<%= link_to 'Show', @season %> |
<%= link_to 'Back', seasons_path %>

app/views/seasons/index.html.erb
<h4>Season Manager</h4>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Meet date</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @seasons.each do |season| %>
  <tr>
    <td><b><%= season.name %></b></td>
    <td><%= season.start_date.strftime("%D") %></td>
    <td><%= season.end_date.strftime("%D") %></td>
    <td><%= season.meet_date.strftime("%D") %></td>
    <td><%= season.active.to_s.upcase %></td>
    <td>
        <% if can? :update, season %>
          <div class="btn-group">
            <%= link_to 'Details', season, :class => "btn btn-small" %>
            <a class="btn btn-small dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit', edit_season_path(season) %></li>
              <li><%= link_to 'Delete', season, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              <li><%= link_to 'Team', teams_url(:season => season.id) %></li>
            </ul>
          </div><!-- /btn-group -->
        <% end %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Season', new_season_path, :class => "btn btn-small btn-primary" %>

app/views/seasons/new.html.erb
<h4>New season</h4>

<%= render 'form' %>

<%= link_to 'Back', seasons_path %>

app/views/seasons/show.html.erb
<!-- TODO: Format all show.html.erb to look more like the edit forms -->

<p id="notice"><%= notice %></p>

<p>
  <b>Start date:</b>
  <%= @season.start_date.strftime("%D") %>
</p>

<p>
  <b>End date:</b>
  <%= @season.end_date.strftime("%D") %>
</p>

<p>
  <b>Meet date:</b>
  <%= @season.meet_date.strftime("%D") %>
</p>

<p>
  <b>Active:</b>
  <%= @season.active %>
</p>

<p>
  <b>Name:</b>
  <%= @season.name %>
</p>


<%= link_to 'Edit', edit_season_path(@season) %> |
<%= link_to 'Back', seasons_path %>