config/routes.rb
SwimTeam2::Application.routes.draw do
  devise_for :users

  resources :events

  resources :seasons

  resources :splits

  resources :swimmers

  resources :families

  resources :teams

  resources :home
  
  root :to => 'home#index'
end

app/models/family.rb
class Family < ActiveRecord::Base
  attr_accessible :c1_email, :c1_first_name, :c1_home_phone, :c1_last_name, :c1_mobile_phone, :c1_relationship, :c1_work_phone, :c2_email, :c2_first_name, :c2_home_phone, :c2_last_name, :c2_mobile_phone, :c2_relationship, :c2_work_phone, :emergency_contact, :name, :user_id

  has_many :swimmers
  belongs_to :user

  def c1_full_name
    "#{c1_first_name} #{c1_last_name}" 
  end

  def c2_full_name
    "#{c2_first_name} #{c2_last_name}" 
  end
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  load_and_authorize_resource
  # GET /families
  # GET /families.json
  def index
    @families = Family.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @families }
    end
  end

  # GET /families/1
  # GET /families/1.json
  def show
    @family = Family.find(params[:id])
    @swimmers = Swimmer.find_all_by_family_id(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @family }
    end
  end

  # GET /families/new
  # GET /families/new.json
  def new
    @family = Family.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @family }
    end
  end

  # GET /families/1/edit
  def edit
    @family = Family.find(params[:id])
  end

  # POST /families
  # POST /families.json
  def create
    @family = Family.new(params[:family])
    @family.user_id = current_user.id
    respond_to do |format|
      if @family.save
        format.html { redirect_to @family, notice: 'Family was successfully created.' }
        format.json { render json: @family, status: :created, location: @family }
      else
        format.html { render action: "new" }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /families/1
  # PUT /families/1.json
  def update
    @family = Family.find(params[:id])
    respond_to do |format|
      if @family.update_attributes(params[:family])
        format.html { redirect_to @family, notice: 'Family was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /families/1
  # DELETE /families/1.json
  def destroy
    @family = Family.find(params[:id])
    @family.destroy

    respond_to do |format|
      format.html { redirect_to families_url }
      format.json { head :no_content }
    end
  end

  before_filter :authenticate_user!
  
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/views/families/_form.html.erb
<%= form_for(@family, :html => { :class => "form-horizontal well"} ) do |f| %>
	<% if @family.errors.any? %>
		<div class="alert alert-error" id="error">
			<%= link_to "x", "#", :class=>"close", :onclick => "document.getElementById('error').style.display='none'" %> 
			<strong>Error! </strong><%= pluralize(@family.errors.count, "error") %> prohibited this family from being saved:
			<ul>
			<% @family.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	<div class="control-group">
		<b><%= f.label :Family_Name, :class => "control-label" %></b>
		<div class="controls">
			<%= f.text_field :name %>
		</div>
	</div>  
	<div>
		<div class="span5">
			<div class="control-group">
				<div class="controls">
					<h4>Primary Contact</h4>
				</div>
				<%= f.label :First_name, :class => "control-label" %>
				<div class="controls">
					<%= f.text_field :c1_first_name %>
				</div>
			</div>
			<div class="control-group">
				<%= f.label :Last_name, :class => "control-label" %>
				<div class="controls">
					<%= f.text_field :c1_last_name %>
				</div>
			</div>
			<div class="control-group">
				<%= f.label :Relationship, :class => "control-label" %>
				<div class="controls">
					<%= f.text_field :c1_relationship %>
				</div>
			</div>
			<div class="control-group">
				<%= f.label :Home_phone, :class => "control-label" %>
				<div class="controls">
					<%= f.text_field :c1_home_phone %>
				</div>
			</div>
			<div class="control-group">
				<%= f.label :Mobile_phone, :class => "control-label" %>
				<div class="controls">
					<%= f.text_field :c1_mobile_phone %>
				</div>
			</div>
			<div class="control-group">
				<%= f.label :Work_phone, :class => "control-label" %>
				<div class="controls">
					<%= f.text_field :c1_work_phone %>
				</div>
			</div>
			<div class="control-group">
				<%= f.label :Email, :class => "control-label" %>
				<div class="controls">
					<%= f.text_field :c1_email %>
				</div>
			</div>
		</div>
		<div class="span5">
			<div class="control-group">
				<div class="controls">
					<h4>Secondary Contact</h4>
				</div>
				<%= f.label :First_name, :class => "control-label" %>
				<div class="controls">
					<%= f.text_field :c2_first_name %>
				</div>
			</div>
			<div class="control-group">
				<%= f.label :Last_name, :class => "control-label" %>
				<div class="controls">
					<%= f.text_field :c2_last_name %>
				</div>
			</div>
			<div class="control-group">
				<%= f.label :Relationship, :class => "control-label" %>
				<div class="controls">
					<%= f.text_field :c2_relationship %>
				</div>
			</div>
			<div class="control-group">
				<%= f.label :Home_phone, :class => "control-label" %>
				<div class="controls">
					<%= f.text_field :c2_home_phone %>
				</div>
			</div>
			<div class="control-group">
				<%= f.label :Mobile_phone, :class => "control-label" %>
				<div class="controls">
					<%= f.text_field :c2_mobile_phone %>
				</div>
			</div>
			<div class="control-group">
				<%= f.label :Work_phone, :class => "control-label" %>
				<div class="controls">
					<%= f.text_field :c2_work_phone %>
				</div>
			</div>
			<div class="control-group">
				<%= f.label :Email, :class => "control-label" %>
				<div class="controls">
					<%= f.text_field :c2_email %>
				</div>
			</div>
		</div>
	</div>

	<div class="span12">
		<div class="control-group">
			<%= f.label :emergency_contact, :class => "control-label" %>
			<div class="controls">
				<%= f.text_area :emergency_contact, :class => "span8" %>
			</div>
		</div>
	</div>
	<div class="control-group actions">
		<div class="controls">
			<%= f.submit(:class=>"btn btn-success") %>
		</div>
	</div>
<% end %>

app/views/families/edit.html.erb
<h4>Editing: Family</h4>

<%= render 'form' %>

<%= link_to 'Show', @family %> |
<%= link_to 'Back', families_path %>

app/views/families/index.html.erb
<h4>Families</h4>

<table class="table">
  <tr>
    <th>Family Name</th>
    <th>1st Contact</th>
    <th>2nd Contact</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @families.each do |family| %>
  <tr>
    <td><%= family.name %></td>
    <td><%= family.c1_full_name %> (<%= family.c1_relationship %>)</td>
    <td><%= family.c2_full_name %> (<%= family.c2_relationship %>)</td>
    <td>
        <% if can? :update, family %>
          <div class="btn-group">
            <%= link_to 'Details', family, :class => "btn btn-small" %>
            <a class="btn btn-small dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit', edit_family_path(family) %></li>
              <li><%= link_to 'Delete', family, method: :delete, data: { confirm: 'Are you sure?' } %></li>
            </ul>
          </div><!-- /btn-group -->
        <% end %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add Family', new_family_path, :class => "btn btn-small btn-primary" %>

app/views/families/new.html.erb
<h4>New Family</h4>

<%= render 'form' %>

<%= link_to 'Back', families_path %>

app/views/families/show.html.erb
<!-- TODO: Format all show.html.erb to look more like the edit forms -->

<p id="notice"><%= notice %></p>

<p><b>Family Name: <%= @family.name %></b></p>

<div class="field-div">
  <p><b>Primary Contact</b></p>
  <p><%= @family.c1_first_name %> <%= @family.c1_last_name %> - <%= @family.c1_relationship %></p>
  <p>Home phone: <%= @family.c1_home_phone == "" ? "None" : number_to_phone(@family.c1_home_phone.to_i, :area_code => true) %></p>
  <p>Mobile phone: <%= @family.c1_mobile_phone == "" ? "None" : number_to_phone(@family.c1_mobile_phone.to_i, :area_code => true) %></p>
  <p>Work phone: <%= @family.c1_work_phone == "" ? "None" : number_to_phone(@family.c1_work_phone.to_i, :area_code => true) %></p>
  <p><%= mail_to(@family.c1_email) %></p>
</div>

<div class = "field-div">
  <p><b>Secondary Contact</b></p>
  <p><%= @family.c2_first_name %> <%= @family.c2_last_name %> - <%= @family.c2_relationship %></p>
  <p>Home phone: <%= @family.c2_home_phone == "" ? "None" : number_to_phone(@family.c2_home_phone.to_i, :area_code => true) %></p>
  <p>Mobile phone: <%= @family.c2_mobile_phone == "" ? "None" : number_to_phone(@family.c2_mobile_phone.to_i, :area_code => true) %></p>
  <p>Work phone: <%= @family.c2_work_phone == "" ? "None" : number_to_phone(@family.c2_work_phone.to_i, :area_code => true) %></p>
  <p><%= mail_to(@family.c2_email) %></p>
</div>

<div class="field-div">
  <p><b>Emergency contact:</b></p>
  <%= @family.emergency_contact %>
</div>
<div class="clear"></div>

<div>
  <p><b>Swimmers</b></p>
  <% @swimmers.each do |swimmer| %>
    <%= link_to(swimmer.full_name, swimmer_path(swimmer.id)) %></p>
  <% end %>
</div>
<%= link_to 'Edit', edit_family_path(@family) %> |
<%= link_to 'Back', families_path %> | <%= link_to 'See Siblings', swimmers_path(:filter => @family.id) %> |
<%= link_to 'Add Swimmer', new_swimmer_path(:family=>@family.id) %>