config/routes.rb
SwimTeam2::Application.routes.draw do
  devise_for :users

  resources :events

  resources :seasons

  resources :splits

  resources :swimmers

  resources :families

  resources :teams

  resources :home
  
  root :to => 'home#index'
end

app/models/swimmer.rb
class Swimmer < ActiveRecord::Base
  attr_accessible :dob, :email, :family_id, :first_name, :gender, :last_name, :shirt_size

  belongs_to :family
  has_many :splits
  has_many :teams
  has_many :seasons, :through => :teams

  validates :dob, :presence => true
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :gender, :presence => true


  def age_in_years
  	age = Date.today.year - self.dob.year
    age -= 1 if Date.today < self.dob + age.years #for days before birthday
    return age
  end

  def full_name
    "#{last_name}, #{first_name}" 
  end
end

app/controllers/swimmers_controller.rb
class SwimmersController < ApplicationController
  load_and_authorize_resource
  # GET /swimmers
  # GET /swimmers.json
  def index
  params[:filter] ? @swimmers = Swimmer.where("family_id = ?", params[:filter]) : @swimmers = Swimmer.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @swimmers }
    end
  end

  # GET /swimmers/1
  # GET /swimmers/1.json
  def show
    @swimmer = Swimmer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @swimmer }
    end
  end

  # GET /swimmers/new
  # GET /swimmers/new.json
  def new
    @swimmer = Swimmer.new
    @swimmer.family_id = params[:family_id]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @swimmer }
    end
  end

  # GET /swimmers/1/edit
  def edit
    @swimmer = Swimmer.find(params[:id])
  end

  # POST /swimmers
  # POST /swimmers.json
  def create
    @swimmer = Swimmer.new(params[:swimmer])
    @swimmer.gender = params[:gender]
    params[:swimmer][:family_id] ? @swimmer.family_id=params[:swimmer][:family_id] : 
    @swimmer.family_id = params[:family_id]
    respond_to do |format|
      if @swimmer.save
        format.html { redirect_to @swimmer, notice: 'Swimmer was successfully created.' }
        format.json { render json: @swimmer, status: :created, location: @swimmer }
      else
        format.html { render action: "new" }
        format.json { render json: @swimmer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /swimmers/1
  # PUT /swimmers/1.json
  def update
    @swimmer = Swimmer.find(params[:id])
    @swimmer.gender = params[:gender]
    respond_to do |format|
      if @swimmer.update_attributes(params[:swimmer])
        format.html { redirect_to @swimmer, notice: 'Swimmer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @swimmer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /swimmers/1
  # DELETE /swimmers/1.json
  def destroy
    @swimmer = Swimmer.find(params[:id])
    @swimmer.destroy

    respond_to do |format|
      format.html { redirect_to swimmers_url }
      format.json { head :no_content }
    end
  end

  before_filter :authenticate_user!
  
end

app/helpers/swimmers_helper.rb
module SwimmersHelper
end

app/views/swimmers/_form.html.erb
<%= form_for(@swimmer, :html => { :name => "timeform", :class => "form-horizontal well"}) do |f| %>
  <% if @swimmer.errors.any? %>
    <div class="alert alert-error" id="error">
      <%= link_to "x", "#", :class=>"close", :onclick => "document.getElementById('error').style.display='none'" %> 
      <strong>Error! </strong><%= pluralize(@swimmer.errors.count, "error") %> prohibited this swimmer from being saved:
      <ul>
      <% @swimmer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :family_id, :class => "control-label" %>
    <div class="controls">
      <% if current_user.admin? %>
        <%= f.collection_select(:family_id, Family.all, :id, :name) %>
      <% else %>
        <%= f.text_field :name, :value=>"#{@current_user.families.first.name}", :disabled => "disabled", :class => "input-large disabled"%>
        <%= hidden_field_tag "family_id", current_user.families.first.id %>
      <% end %>
    </div>
  </div>  
  <div class="control-group">
    <%= f.label :first_name, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :first_name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :last_name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :gender, :class => "control-label" %>
    <div class="controls">
      <select name="gender">
        <option value="Female">Female</option>
        <option value="Male">Male</option>
      </select>
    </div>
    
  </div>
  <div class="control-group">
    <%= f.label :dob, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :dob, :class => "date_picker" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :email %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :shirt_size, :class => "control-label" %>
    <div class="controls">
      <%= f.collection_select(:shirt_size, Shirt.all, :size, :size) %>
    </div>
  </div>
  <div class="control-group actions">
    <div class="controls">
      <%= f.submit(:class=>"btn btn-success") %>
    </div>
  </div>
<% end %>

app/views/swimmers/edit.html.erb
<h1>Editing swimmer</h1>

<%= render 'form' %>

<%= link_to 'Show', @swimmer %> |
<%= link_to 'Back', swimmers_path %>

app/views/swimmers/index.html.erb
<h4>Swimmers</h4>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Gender</th>
    <th>Age</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @swimmers.each do |swimmer| %>
  <tr>
    <td><b><%= swimmer.last_name %></b>, <%= swimmer.first_name %></td>
    <td><%= swimmer.gender.first %></td>
    <td><%= swimmer.age_in_years %></td>
    <td><%= mail_to(swimmer.email) %></td>
    <td>
        <% if can? :update, swimmer %>
          <div class="btn-group">
            <%= link_to 'Details', swimmer, :class => "btn btn-small" %>
            <a class="btn btn-small dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit', edit_swimmer_path(swimmer) %></li>
              <li><%= link_to 'Delete', swimmer, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              <li><%= link_to 'Splits', splits_path(:filter => swimmer.id) %></li>
            </ul>
          </div><!-- /btn-group -->
        <% end %>
    </td>
    <td>
        <% if can? :update, swimmer %>
          <div class="btn-group">
            <%= link_to 'Family', "#", :class => "btn btn-small" %>
            <a class="btn btn-small dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Family', family_path(:id => swimmer.family_id) %></li>
              <li><%= link_to 'Siblings', swimmers_path(:filter => swimmer.family_id) %></li>
            </ul>
          </div><!-- /btn-group -->
        <% end %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Swimmer', new_swimmer_path, :class => "btn btn-small btn-primary" %>

app/views/swimmers/new.html.erb
<h4>New swimmer</h4>

<%= render 'form' %>

<%= link_to 'Back', swimmers_path %>

app/views/swimmers/show.html.erb
<!-- TODO: Format all show.html.erb to look more like the edit forms -->

<p id="notice"><%= notice %></p>

<p>
  <b>Family:</b>
  <%= @swimmer.family.name %>
</p>

<p>
  <b>First name:</b>
  <%= @swimmer.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @swimmer.last_name %>
</p>

<p>
  <b>Gender:</b>
  <%= @swimmer.gender %>
</p>

<p>
  <b>Dob:</b>
  <%= @swimmer.dob.strftime("%D") %>
</p>

<p>
  <b>Email:</b>
  <%= mail_to(@swimmer.email) %>
</p>

<p>
  <b>Shirt size:</b>
  <%= @swimmer.shirt_size %>
</p>


<%= link_to 'Edit', edit_swimmer_path(@swimmer) %> |
<%= link_to 'Back', swimmers_path %>