config/routes.rb
SwimTeam2::Application.routes.draw do
  devise_for :users

  resources :events

  resources :seasons

  resources :splits

  resources :swimmers

  resources :families

  resources :teams

  resources :home
  
  root :to => 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SwimCoach" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-block",:id => "flash_#{name}" do %>
        <%= msg %>
        <%= content_tag :span, :style => "float: right;" do %>
          <%= link_to "x", "#", :class=>"close", :onclick => "document.getElementById('flash_#{name}').style.display='none'" %> 
        <% end %>
      <% end %>
    <% end %>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_path %>">SwimCoach</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <% if current_user.try(:admin?) %>
                <li><%= link_to "Seasons", seasons_path  %></li>
                <li><%= link_to "Families", families_path  %></li>
                <li><%= link_to "Swimmers", swimmers_path  %></li>
                <li><%= link_to "Splits", splits_path  %></li>
              <% end %>
            </ul>
            <ul class="nav pull-right" id="main-menu-right">
              <% if user_signed_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'My Account', edit_user_registration_url %></li>
                    
                    <% if current_user.admin? %>
                      <!-- <li><%= link_to 'Admin Stuff - Fix', "#" %></li>
                      <li><%= link_to 'More Admin Stuff - Fix', "#" %></li> -->
                    <% else %>
                      <li><%= link_to 'My Family', edit_family_path(current_user.families.first.id) %></li>
                      <li><%= link_to 'My Swimmer(s)', swimmers_path(:filter => current_user.families.first.id) %></li>
                    <% end %>
                    <li><%= link_to 'Log out', destroy_user_session_url, method: :delete, data: { confirm: 'Are you sure you want to logout?' } %></li>
                    
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
                <li><%= link_to "Log In", new_user_session_path %></li>
              <% end %>
              
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
            <div class="span12">
              <%= yield %>
            </div>
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p class="pull-right">&copy; KsAvsFan 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>